{% set version = "3.1.5" %}

package:
  name: openpyxl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/openpyxl/openpyxl-{{ version }}.tar.gz
  sha256: cf0e3cf56142039133628b5acffe8ef0c12bc902d2aadd3e0fe5878dc08d1050

build:
  number: 2
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --global-option="--with-cython"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
  host:
    - python
    - pip >=18.0
    - cython
    - {{ compiler('c') }}
    - setuptools
  run:
    - python
    - et_xmlfile

test:
  imports:
    - openpyxl
    - openpyxl.cell
    - openpyxl.chart
    - openpyxl.chartsheet
    - openpyxl.comments
    - openpyxl.compat
    - openpyxl.descriptors
    - openpyxl.drawing
    - openpyxl.formatting
    - openpyxl.formula
    - openpyxl.packaging
    - openpyxl.pivot
    - openpyxl.reader
    - openpyxl.styles
    - openpyxl.utils
    - openpyxl.workbook
    - openpyxl.workbook.external_link
    - openpyxl.worksheet
    - openpyxl.writer
    - openpyxl.xml

about:
  home: https://openpyxl.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENCE.rst
  summary: A Python library to read/write Excel 2010 xlsx/xlsm files
  description: |
    openpyxl is a Python library to read/write Excel 2010
    xlsx/xlsm/xltx/xltm files.
  doc_url: https://openpyxl.readthedocs.io/en/stable/
  dev_url: https://foss.heptapod.net/openpyxl/openpyxl/

extra:
  recipe-maintainers:
    - thewchan
    - curtisalexander
    - ocefpaf
